---
- hosts:  all 
  become: yes
  tasks:

  - name: Add User opencast
    user:
      name: opencast
      shell: /bin/bash
      groups: audio,video
      append: yes

  - name: install Dependencies
    dnf:
      name={{ item }} state=installed
    with_items:
      - python-icalendar
      - python-dateutil
      - ntpdate
      - python-pycurl
      - python-configobj
      - python-flask
      - python-sqlalchemy
      - ffmpeg
      - rsync

  - name: create folder
    file:
     path: /opt/pyCA
     state: directory
     mode: 0755

  - name: copy pyca
    copy: src=./pyCA/ dest=/opt/pyCA/ owner=opencast group=opencast mode=755

  - name: set owner and group
    file: path=/opt/pyCA owner=opencast group=opencast mode=755


  - name: enable autostart pyCA
    copy:
     src: ./pyCA/bin/
     dest: /etc/systemd/system/

  - name: enable autostart
    command: "systemctl enable pyca.service"

  - name: set Hostname
    command: hostnamectl set-hostname {{inventory_hostname}}

  - name: install xymon-client
    apt:
     state: present
     name: xymon-client
