---
- hosts:  131.173.172.68
  become: yes
  tasks:

  - name: Install rpm-fusion 
    command: "dnf -y install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-26.noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-26.noarch.rpm"

     
  - name: copy rec.sh
    copy: src=rec.sh  dest=/opt/pyCA/ owner=opencast group=opencast mode=0644

  - name: install Dependencies
    dnf:
      name={{ item }} state=installed
    with_items:
      - python-icalendar
      - python-dateutil
      - ntpdate
        #      - xymon-client
      - python-pycurl
      - python-configobj
      - python-flask
      - python-sqlalchemy
      - ffmpeg
      - rsync

  - name: copy pyca
    copy: 
     src: ./pyCA/ 
     dest: /opt/ 

  - name: set owner and group
    file: path=/home/opt/pyCA owner=opencast group=opencast mode=0644
    

  - name: enable autostart pyCA
    copy:
     srv: ./bin/
     dest: /etc/system.d/system/
