---
- hosts:  all 
  become: yes
  tasks:

  - name: Add User opencast
    user:
      name: opencast
      shell: /bin/bash
      groups: audio,video
      append: yes

  - name: install epel-release 
    dnf:
     name: http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-28.noarch.rpm
     state: installed

  - name: install Dependencies
    dnf:
      name={{ item }} state=installed
    with_items:
      - python-icalendar
      - python-dateutil
      - ntpdate
      - python-pycurl
      - python-configobj
      - python-flask
      - python-sqlalchemy
      - ffmpeg
      - rsync
      - libselinux-python
      - libva-intel-driver

  - name: create folder
    file:
     path: /opt/pyCA
     state: directory
     mode: 0755

  - name: copy pyca
    copy: src=./pyCA/ dest=/opt/pyCA/ owner=opencast group=opencast mode=755

  - name: set owner and group
    file: path=/opt/pyCA owner=opencast group=opencast mode=755


  - name: enable autostart pyCA
    copy:
     src: ./pyCA/bin/
     dest: /etc/systemd/system/

  - name: enable autostart
    command: "systemctl enable pyca.service"

  - name: set Hostname
    command: hostnamectl set-hostname {{inventory_hostname}}

  - name: download xymon-client
    get_url: 
     url: http://terabithia.org/rpms/xymon/f25/x86_64/xymon-client-4.3.28-1.fc25.x86_64.rpm
     dest: /home/opencast/

  - name: install xymon-client
    command: dnf -y install /home/opencast/xymon-client-4.3.28-1.fc25.x86_64.rpm

